import type { NextPage } from 'next';
import Head from 'next/head';
import { useEffect } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import { useActions } from '../../redux';
import styles from '../../styles/Home.module.css';

const Posts: NextPage = () => {
    const dispatch = useDispatch();
    const posts = useSelector((state: any) => state.posts.posts);
    const actions = useActions();

    useEffect(() => {
        dispatch(actions.PostActions.loadListPosts());
    }, []);

    return (
        <div className={styles.container}>
            <Head>
                <title>Posts Page</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            {posts.map((post: any, index: any) => {
                return (
                    <div>
                        <h3>{post.title}</h3>
                        {post.content}
                    </div>
                );
            })}
        </div>
    );
};

export default Posts;
