import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

const GetNumbers: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Get Numbers Page</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <h3>GetNumber Page</h3>
        </div>
    );
};

export default GetNumbers;
