import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { useDispatch } from 'react-redux';
import { useActions } from '../redux';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
    const dispatch = useDispatch();
    const actions = useActions();

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <h3>Home Page</h3>
        </div>
    );
};

export default Home;
