import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { useRouter } from 'next/router';
import { useState } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import { useActions } from '../redux';
import styles from '../styles/Login.module.scss';
import Link from 'next/link';

const Login: NextPage = () => {
    const isLoggedIn = useSelector((state: any) => state.auth.isLoggedIn);
    const router = useRouter();

    const dispatch = useDispatch();
    const actions = useActions();

    let [username, setUserName] = useState('');
    let [password, setPassword] = useState('');

    if (isLoggedIn) {
        const returnUrl: any = router.query.returnUrl || '';
        // router.push(returnUrl);

        router.push({
            pathname: returnUrl,
            query: {
                returnUrl: router.asPath,
            },
        });
    }

    const _handleLogin = () => {
        dispatch(actions.AuthActions.login(username, password));
    };

    return (
        <div className={styles.LoginPage}>
            <Head>
                <title>Login Page</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={styles.LoginPanel}>
                <div className={styles.RowInfo}>
                    <div className={styles.RowInfoTitle}>Username</div>
                    <div className={styles.RowInfoContent}>
                        <input
                            value={username}
                            onChange={(e) => {
                                setUserName(e.target.value);
                            }}
                            type="text"
                            className={styles.RowInfoTextBox}
                            onKeyPress={(e) => {
                                if (e.key === 'Enter') _handleLogin();
                            }}
                        />
                    </div>
                </div>

                <div className={styles.RowInfo}>
                    <div className={styles.RowInfoTitle}>Password</div>
                    <div className={styles.RowInfoContent}>
                        <input
                            value={password}
                            onChange={(e) => {
                                setPassword(e.target.value);
                            }}
                            type="password"
                            className={styles.RowInfoTextBox}
                            onKeyPress={(e) => {
                                if (e.key === 'Enter') _handleLogin();
                            }}
                        />
                    </div>
                </div>

                <div
                    className={styles.ControlPanel}
                    onClick={() => {
                        _handleLogin();
                    }}
                >
                    <div className={styles.Button}>Login</div>
                </div>

                <div
                    style={{ marginTop: 5 }}
                    className={styles.ControlPanel}
                >
                    <Link href="/register">
                        <div
                            style={{ backgroundColor: '#33cc33' }}
                            className={styles.Button}
                        >
                            Register
                        </div>
                    </Link>
                </div>
            </div>
        </div>
    );
};

export default Login;
