import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { useRouter } from 'next/router';
import { useState } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import { useActions } from '../redux';
import styles from '../styles/Home.module.css';

const Login: NextPage = () => {
    const isLoggedIn = useSelector((state: any) => state.auth.isLoggedIn);
    const router = useRouter();

    const dispatch = useDispatch();
    const actions = useActions();

    let [username, setUsername] = useState('');
    let [password, setPassword] = useState('');

    if (isLoggedIn)
        router.push({
            pathname: '/',
            query: {
                returnUrl: router.asPath,
            },
        });

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <h3>Tài khoản</h3>
            <input
                type="text"
                value={username}
                onChange={(e) => {
                    setUsername(e.target.value);
                }}
            />

            <h3>Mật khẩu</h3>
            <input
                type="text"
                value={password}
                onChange={(e) => {
                    setPassword(e.target.value);
                }}
            />

            <br />
            <button
                onClick={() => {
                    dispatch(actions.AuthActions.login(username, password));
                }}
            >
                Đăng nhập
            </button>
        </div>
    );
};

export default Login;
