import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { useSelector } from 'react-redux';
import styles from '../styles/Home.module.css';

const Login: NextPage = () => {
    const isLoggedIn = useSelector((state: any) => state.auth.isLoggedIn);

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <h1>Login Page</h1>
            <h3>{isLoggedIn ? "True" : "False"}</h3>
        </div>
    );
};

export default Login;
