import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { useState } from 'react';
import styles from '../styles/Home.module.css';

const Register: NextPage = () => {
    const [count, setCount] = useState(10);

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <h1>Register Page</h1>

            <h2>{count}</h2>
            <button
                onClick={() => {
                    setCount(count + 10);
                }}
            >
                +
            </button>
        </div>
    );
};

export default Register;
